branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

matrix:
  include:
    - dist: bionic
      env: PGB_CI="test --vm=u18 --vm-arch=ppc64le --sudo"

install:
  - umask 0022 && cd ~ && pwd && whoami && umask && groups
  - df -Th && top -bn1

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
