branches:
  only:
    - integration
    - /-ci$/

dist: trusty
sudo: required

language: c

services:
  - docker

matrix:
  include:
    - env: PGB_CI="test --vm=u12"
    - env: PGB_CI="test --vm=f30 --param=c-only"
    - env: PGB_CI="test --vm=co6 --param=build-package --param=module=mock --param=module=real"
    - env: PGB_CI="test --vm=u18 --param=build-package --param=container-only"
    - env: PGB_CI=" doc --vm=u18"
    - env: PGB_CI="test --vm=co7 --param=build-package --param=module=mock --param=module=real"
    - dist: bionic
      env:
        - PGB_CI="test --vm=none --param=tz=America/New_York"
      services:
    - env: PGB_CI=" doc --vm=co6"
    - env: PGB_CI=" doc --vm=co7"

install:
  - umask 0022 && cd ~ && pwd && whoami && umask && groups
  - df -Th && top -bn1

script:
  - ${TRAVIS_BUILD_DIR?}/test/travis.pl ${PGB_CI?}
